language: r
sudo: false
cache: packages

before_install:
  - tlmgr install bera

warnings_are_errors: false

r: bioc-devel
r_build_args: --no-build-vignettes
r_check_args: --no-vignettes --force-multiarch

bioc_packages: BiocCheck

r_github_packages:
  - jimhester/covr
  
after_script:
  - R CMD BiocCheck *tar.gz  

after_success:
  - Rscript -e 'covr::codecov()'
