language: r
sudo: false
cache: packages

before_install:
  - tlmgr install bera

warnings_are_errors: false

r: bioc-devel

bioc_packages: BiocCheck

r_github_packages:
  - jimhester/covr
  
after_script:
  - R CMD BiocCheck *tar.gz  

after_success:
  - Rscript -e 'covr::codecov()'
